variables:
  poolName: blk902001 - Lyreco Agent Pool

resources:
  repositories:
    - repository: bc-at-demo
      type: github
      endpoint: Zakrzewski-Rafal-Dev
      name: bc-at-demo
      ref: main
      trigger:
        branches:
          include:
            - main

    - repository: templates
      type: git
      name: DevOps/DevOps
      ref: master

stages:
  - template: templates/common/buildAcceptanceTests.yml@templates
    parameters:
      dotnetVersion: 6.0.406
      artifactName: AcceptanceTests
      repositoryName: bc-at-demo
      poolName: $(poolName)
      buildConfiguration: Release
